role:
  unverified:
    - "hs:hs_auth:frontend:EmailUnverifiedPage"
    - "hs:hs_auth:frontend:EmailUnverifiedPageComponents"
    - "hs:hs_auth:frontend:VerifyEmailResend"
    - "hs:hs_auth:api:v2:ResendEmailVerification?path_id=me"
    - "hs:hs_auth:api:v2:GetAuthorizedResources"
  applicant:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:frontend:ProfilePageComponents:TeamPanel"
    - "hs:hs_auth:frontend:CreateTeam"
    - "hs:hs_auth:frontend:JoinTeam"
    - "hs:hs_auth:frontend:LeaveTeam"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:GetUsers?query_team=me"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:SetTeam?path_id=me"
    - "hs:hs_auth:api:v2:RemoveFromTeam?path_id=me"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_auth:api:v2:GetAuthorizedResources"
    - "hs:hs_apply:Dashboard:dashboard"
    - "hs:hs_apply:Application:apply"
    - "hs:hs_apply:Application:updatePartialApplication"
    - "hs:hs_apply:Application:submitApplication"
    - "hs:hs_apply:Application:cancel"
  attendee:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:frontend:ProfilePageComponents:TeamPanel"
    - "hs:hs_auth:frontend:CreateTeam"
    - "hs:hs_auth:frontend:JoinTeam"
    - "hs:hs_auth:frontend:LeaveTeam"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:GetUsers?query_team=me"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:SetTeam?path_id=me"
    - "hs:hs_auth:api:v2:RemoveFromTeam?path_id=me"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_auth:api:v2:GetAuthorizedResources"
    - "hs:hs_apply:Dashboard:dashboard"
    - "hs:hs_apply:Application:cancel"
    - "hs:hs_hub"
  volunteer:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:api:v2:GetUser"
    - "hs:hs_auth:api:v2:GetUsers"
    - "hs:hs_auth:api:v2:GetTeams"
    - "hs:hs_auth:api:v2:GetAuthorizedResources"
    - "hs:hs_apply:Dashboard:dashboard"
    - "hs:hs_apply:Application:apply"
    - "hs:hs_apply:Application:updatePartialApplication"
    - "hs:hs_apply:Application:submitApplication"
    - "hs:hs_apply:Application:cancel"
    - "hs:hs_hub"
  organiser:
    - "hs"