role:
  # TODO: review permissions for roles after Auth System V2 is finished (https://github.com/unicsmcr/hs_auth/issues/81)
  unverified:
    - "hs:hs_auth:frontend:EmailUnverifiedPage"
    - "hs:hs_auth:frontend:EmailUnverifiedPageComponents"
    - "hs:hs_auth:frontend:VerifyEmailResend"
  applicant:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:frontend:ProfilePageComponents:TeamPanel"
    - "hs:hs_auth:frontend:CreateTeam"
    - "hs:hs_auth:frontend:JoinTeam"
    - "hs:hs_auth:frontend:LeaveTeam"
    - "hs:hs_auth:api:v2:Register"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:Login"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_apply:apply"
  attendee:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:frontend:ProfilePageComponents:TeamPanel"
    - "hs:hs_auth:frontend:CreateTeam"
    - "hs:hs_auth:frontend:JoinTeam"
    - "hs:hs_auth:frontend:LeaveTeam"
    - "hs:hs_auth:api:v2:Register"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:Login"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_apply:apply"
    - "hs:hs_hub"
  volunteer:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:api:v2:Register"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:Login"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_apply:apply"
    - "hs:hs_hub"
    - "hs:hs_apply:review"
  organiser:
    - "hs"