role:
  # TODO: review permissions for roles after Auth System V2 is finished (https://github.com/unicsmcr/hs_auth/issues/81)
  unverified:
    - "hs:hs_auth:frontend:Logout"
    - "hs:hs_auth:frontend:EmailUnverifiedPage"
    - "hs:hs_auth:frontend:VerifyEmailResend"
  applicant:
    - "hs:hs_auth:frontend:Logout"
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:api:v2:Register"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:Login"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_applications:apply"
  attendee:
    - "hs:hs_auth:frontend:Logout"
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:api:v2:Register"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:Login"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_applications:apply"
    - "hs:hs_hub"
  volunteer:
    - "hs:hs_auth:frontend:Logout"
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:api:v2:Register"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:Login"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_applications:apply"
    - "hs:hs_hub"
    - "hs:hs_applications:review"
  organiser:
    - "hs"