role:
  unverified:
    - "hs:hs_auth:frontend:EmailUnverifiedPage"
    - "hs:hs_auth:frontend:EmailUnverifiedPageComponents"
    - "hs:hs_auth:frontend:VerifyEmailResend"
    - "hs:hs_auth:api:v2:ResendEmailVerification?path_id=me"
    - "hs:hs_auth:api:v2:GetAuthorizedResources?query_user="
  applicant:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:frontend:ProfilePageComponents:TeamPanel"
    - "hs:hs_auth:frontend:CreateTeam"
    - "hs:hs_auth:frontend:JoinTeam"
    - "hs:hs_auth:frontend:LeaveTeam"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:GetUsers?query_team=me"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:SetTeam?path_id=me"
    - "hs:hs_auth:api:v2:RemoveFromTeam?path_id=me"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_apply:frontend:NavbarComponent"
    - "hs:hs_auth:api:v2:GetAuthorizedResources?query_user="
    - "hs:hs_apply:Dashboard:dashboard"
    - "hs:hs_apply:Application:apply"
    - "hs:hs_apply:Application:updatePartialApplication"
    - "hs:hs_apply:Application:submitApplication"
    - "hs:hs_apply:Application:cancel"
    - "hs:hs_apply:Invite:confirm"
  attendee:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:frontend:ProfilePageComponents:TeamPanel"
    - "hs:hs_auth:frontend:CreateTeam"
    - "hs:hs_auth:frontend:JoinTeam"
    - "hs:hs_auth:frontend:LeaveTeam"
    - "hs:hs_auth:api:v2:GetUser?path_id=me"
    - "hs:hs_auth:api:v2:GetUsers?query_team=me"
    - "hs:hs_auth:api:v2:CreateTeam"
    - "hs:hs_auth:api:v2:SetTeam?path_id=me"
    - "hs:hs_auth:api:v2:RemoveFromTeam?path_id=me"
    - "hs:hs_auth:api:v2:GetTeam?path_id=me"
    - "hs:hs_apply:frontend:NavbarComponent"
    - "hs:hs_auth:api:v2:GetAuthorizedResources?query_user="
    - "hs:hs_apply:Dashboard:dashboard"
    - "hs:hs_apply:Application:cancel"
    - "hs:hs_hub:User"
    - "hs:hs_hub:Schedule:listEvents"
    - "hs:hs_hub:Map"
    - "hs:hs_hub:Home"
    - "hs:hs_hub:Challenge:listChallenges"
    - "hs:hs_hub:Achievements:getProgressForAllAchievements"
    - "hs:hs_hub:Achievements:getProgressForAchievement"
    - "hs:hs_hub:Achievements:getAchievementsPage"
    - "hs:hs_discord:guild:attendee"
    - "hs:hs_discord:bot:sync"
  volunteer:
    - "hs:hs_auth:frontend:ProfilePage"
    - "hs:hs_auth:frontend:ProfilePageComponents:Default"
    - "hs:hs_auth:api:v2:GetUser"
    - "hs:hs_auth:api:v2:GetUsers"
    - "hs:hs_auth:api:v2:GetTeams"
    - "hs:hs_apply:frontend:NavbarComponent"
    - "hs:hs_auth:api:v2:GetAuthorizedResources?query_user="
    - "hs:hs_apply:Dashboard:dashboard"
    - "hs:hs_hub:User"
    - "hs:hs_hub:Schedule:listEvents"
    - "hs:hs_hub:Map"
    - "hs:hs_hub:Home"
    - "hs:hs_hub:Challenge:listChallenges"
    - "hs:hs_hub:Achievements"
    - "hs:hs_discord:guild:volunteer"
    - "hs:hs_discord:bot"
  organiser:
    - "hs"
