version: '3.6'

services:
  hs_auth:
    image: hs_auth:latest
    ports:
      - 8080:8080
    env_file:
      - app.env
    volumes:
      - ./:/go/src/github.com/unicsmcr/hs_auth
    depends_on:
      - mongo
    networks:
      - internal
      - hacker_suite

  # database used by app
  mongo:
    image: mongo:4
    restart: always
    env_file:
      - mongo.env
    networks:
      - internal

  # graphical DB management platform (available at localhost:8081)
  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - mongo_express.env
    depends_on:
      - mongo
    networks:
      - internal

networks:
  # internal network for hs_auth services
  internal:
    driver: bridge
  # external network for consumer-facing hacker suite services
  hacker_suite:
    external:
      name: hacker_suite
