version: '3.5'

services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/unicsmcr/hs_auth
    ports:
      - 8080:8080
    env_file:
      - app.env
    networks:
      - internal
      - hacker_suite

  mongo:
    image: mongo:4
    restart: always
    env_file:
      - mongo.env
    networks:
      - internal

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - mongo_express.env
    networks:
      - internal

networks:
  internal:
    driver: bridge
  hacker_suite:
    name: hacker_suite
    driver: bridge
