// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/unicsmcr/hs_auth/config"
	"github.com/unicsmcr/hs_auth/environment"
	"github.com/unicsmcr/hs_auth/repositories"
	"github.com/unicsmcr/hs_auth/routers"
	"github.com/unicsmcr/hs_auth/routers/api/v1"
	"github.com/unicsmcr/hs_auth/routers/frontend"
	"github.com/unicsmcr/hs_auth/services"
	"github.com/unicsmcr/hs_auth/services/mongo"
	"github.com/unicsmcr/hs_auth/services/sendgrid"
	"github.com/unicsmcr/hs_auth/utils"
)

// Injectors from wire.go:

func InitializeServer() (Server, error) {
	logger, err := utils.NewLogger()
	if err != nil {
		return Server{}, err
	}
	env := environment.NewEnv(logger)
	appConfig, err := config.NewAppConfig(env)
	if err != nil {
		return Server{}, err
	}
	database, err := utils.NewDatabase(logger, env)
	if err != nil {
		return Server{}, err
	}
	userRepository, err := repositories.NewUserRepository(database)
	if err != nil {
		return Server{}, err
	}
	userServiceV2 := mongo.NewMongoUserService(logger, env, appConfig, userRepository)
	client := utils.NewSendgridClient(env)
	emailServiceV2, err := sendgrid.NewSendgridEmailService(logger, appConfig, client, userServiceV2)
	if err != nil {
		return Server{}, err
	}
	teamRepository, err := repositories.NewTeamRepository(database)
	if err != nil {
		return Server{}, err
	}
	teamServiceV2 := mongo.NewMongoTeamService(logger, env, teamRepository, userServiceV2)
	apiv1Router := v1.NewAPIV1Router(logger, appConfig, env, userServiceV2, emailServiceV2, teamServiceV2)
	userService := services.NewUserService(logger, userRepository)
	teamService := services.NewTeamService(logger, teamRepository)
	emailService, err := services.NewEmailClient(logger, appConfig, env)
	if err != nil {
		return Server{}, err
	}
	router := frontend.NewRouter(logger, appConfig, env, userService, teamService, emailService)
	mainRouter := routers.NewMainRouter(logger, apiv1Router, router)
	server := NewServer(mainRouter, env)
	return server, nil
}
