version: '2.1'

services:
  mongo:
    image: mongo:4
    volumes:
      - ../../initial_db_setup.sh:/docker-entrypoint-initdb.d/initial_db_setup.sh:ro
    env_file:
      - env_test
    ports:
      - 8003:27017
