# Store non-sensitive project configuration here
name: "Hacker Suite - Auth"
email:
  noreply_email_addr: "noreply@unicsmcr.com"
  help_email_addr: "help@unicsmcr.com"
  noreply_email_name: "UniCS"
  email_verification_email_subj: "Verify email"
  password_reset_email_subj: "Reset password"
  token_lifetime: 108000 # 30 hours
app_url: "auth.unicsmcr.com"
data_policy_url: "https://drive.google.com/file/d/1wMcJbfEhIp9FjdNbyom4RVUoTH4xc0OB/view"
team_members_soft_limit: 4
auth:
  user_token_lifetime: 108000 # 30 hours
  default_role: "unverified"
  email_verification_required: true
  default_email_verified_role: "applicant"