# Store non-sensitive project configuration here
name: "Hacker Suite - Auth"
# the default auth level for new users (auth levels defined in authLevel.go)
base_auth_level: 0
# the lifetime of auth tokens in seconds
auth_token_lifetime: 108000 # 30 hours
email:
  noreply_email_addr: "noreply@unicsmcr.com"
  help_email_addr: "help@unicsmcr.com"
  noreply_email_name: "UniCS"
  email_verification_email_subj: "Verify email"
  password_reset_email_subj: "Reset password"
app_url: "auth.unicsmcr.com"
