# Store non-sensitive project configuration here
name: "GreatUniHack 2020"
email:
  email_delivery_provider: "smtp"
  noreply_email_addr: "noreply@greatunihack.com"
  help_email_addr: "help@greatunihack.com"
  noreply_email_name: "GreatUniHack"
  email_verification_email_subj: "Verify email"
  password_reset_email_subj: "Reset password"
  token_lifetime: 108000 # 30 hours
app_url: "auth.greatunihack.com"
data_policy_url: "https://docs.google.com/document/d/1M0uaD0jDUr9bU7uaPwmFDRk4b9t0RgG9yl_mpoOdoN4/edit?usp=sharing"
team_members_soft_limit: 4
auth:
  user_token_lifetime: 108000 # 30 hours
  default_role: "unverified"
  email_verification_required: true
  default_email_verified_role: "applicant"
